package com.product;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Properties;

import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


import com.customer.Customer;


@WebServlet("/CheckOutServlet")
public class CheckOutServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		PrintWriter out = response.getWriter();
		response.setContentType("text/html");
		
		String name = request.getParameter("name");
		String address = request.getParameter("address");
		String phone = request.getParameter("phone");
		String total = request.getParameter("total");
		double convertedTotal = Double.parseDouble(total);
		
		String fromEmail = "greensupermarket386@gmail.com";
		 String password = "oesp uebx kctk xnze";
		 
		 String toEmail = "greensupermarket246@gmail.com";
		 //String toEmail = "missakarathnapriya@gmail.com";
		 
		 Properties props = new Properties();
		 props.put("mail.smtp.host", "smtp.gmail.com");
		 props.put("mail.smtp.port", "587");
		 props.put("mail.smtp.auth", "true");
		 props.put("mail.smtp.starttls.enable", "true");	
		 
		 Session session = Session.getInstance(props, new Authenticator() {
			 protected PasswordAuthentication getPasswordAuthentication() {
	                return new PasswordAuthentication(fromEmail, password);
	            }
		 });
		
		int orderId = ProductDBUtil.getorderId();
		int incrementedId = orderId + 1;
		
		ArrayList<Cart> cart_list = (ArrayList<Cart>) request.getSession().getAttribute("cart-list");
		Customer authenticate = (Customer) request.getSession().getAttribute("authenticate");
		if(authenticate != null) {
			 toEmail = authenticate.getEmail();
		}
		System.out.println("cart list" + cart_list);
		System.out.println("authenticate" + authenticate);
		try {						
			if(cart_list != null && authenticate != null) {			
				for(Cart c:cart_list) {
					Order order = new Order();
					order.setId(c.getId());
					order.setCustomerId(authenticate.getId());
					order.setOrderQty(c.getQuantity()); 
					
					boolean isTrue = ProductDBUtil.addOrder(order, incrementedId);
					if(!isTrue) {
						break;
					}
				}
				cart_list.clear();
				ProductDBUtil.updateorderId(incrementedId, orderId);
				boolean shipping = ProductDBUtil.shippingDetails(incrementedId, authenticate.getId(), name, phone, address, convertedTotal);
				Message message = new MimeMessage(session);
				 message.setFrom(new InternetAddress(fromEmail));
				 message.addRecipient(javax.mail.Message.RecipientType.TO, new InternetAddress(toEmail));
				 message.setSubject("Order successfully");
				 message.setText("Your Total bill value Rs" + total+ "\n\nDear " + name+ " This email is generated by an automated system and is for informational purposes only. Please be advised that replies to this email will not be monitored or attended to. If you have any inquiries or require assistance, kindly visit our website GreenSupermarket.com or contact our customer support at greensupermarket386@gmail.com. Thankyou" );
				 
				 
				 

				 Transport.send(message);
				response.sendRedirect("payment.jsp");
			}else {
				if(authenticate != null) {
					response.sendRedirect("login.jsp");
				}
				response.sendRedirect("home.jsp");
			}
		}catch(Exception e) {
			e.printStackTrace();
		}
	}

}
